[package]
name = "okerrr"
version = "0.1.0-rc.1"
edition = "2021"
rust-version = "1.56"
authors = ["Adam Williams"]
description = "programmatic freedom from matching Result<T, E>—okerrr!"
readme = "README.md"
include = ["/src/**", "/tests/**", "/README.md", "/LICENSE-*"]
repository = "https://github.com/awill1988/okerrr"
license = "MIT OR Apache-2.0"
keywords = ["macros", "error-handling", "pattern-matching", "control-flow", "result"]
categories = ["rust-patterns", "no-std", "development-tools"]

[features]
default = []
