[package]
name = "okerrr"
version = "0.0.0"
edition = "2021"
rust-version = "1.56"
authors = ["Adam Williams"]
description = "programmatic freedom from matching Result<T, E>—okerrr!"
readme = "README.md"
exclude = ["node_modules/", "package*.json", "commitlint.config.cjs", "cliff.toml", "scripts/", ".githooks/", ".github/"]
repository = "https://github.com/awill1988/okerrr"
license = "MIT OR Apache-2.0"
keywords = ["macros", "error-handling", "pattern-matching", "control-flow", "result"]
categories = ["rust-patterns", "no-std", "development-tools"]

[features]
default = []
